{
 "title": "TrainingJobs",
 "tags": [
  "arms-k8s",
  "c3c5ffe0a9a0542bab3b3819d891542c7",
  "kube-ai-training-job-details"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "45s",
 "templating": {
  "list": [
   {
    "name": "job_namespace",
    "query": "label_values({__name__=~\"arena_duration_of_training_job\"},job_namespace)"
   },
   {
    "name": "job_type",
    "query": "label_values({__name__=~\"arena_duration_of_training_job\",job_namespace=~\"$job_namespace\"},job_type)"
   },
   {
    "name": "job_name",
    "query": "label_values({__name__=~\"arena_duration_of_training_job\",job_type=~\"$job_type\"},job_name)"
   },
   {
    "name": "job_status",
    "query": "label_values({__name__=~\"arena_duration_of_training_job\"},job_status)"
   }
  ]
 },
 "panels": [
  { "title": "Training Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Training Jobs",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(arena_duration_of_training_job{job_namespace=~\"$job_namespace\",job_name=~\"$job_name\",job_status=~\"$job_status\",job_type=~\"$job_type\"}[30s] )",
     "legendFormat": "Duration"
    },
    {
     "expr": "max_over_time(arena_used_gpu_memory_of_training_job{job_namespace=~\"$job_namespace\",job_name=~\"$job_name\",job_status=~\"$job_status\",job_type=~\"$job_type\"}[30s])",
     "legendFormat": "Used GPU Memory"
    },
    {
     "expr": "max_over_time(arena_gpu_utilization_of_training_job{job_namespace=~\"$job_namespace\",job_name=~\"$job_name\",job_status=~\"$job_status\",job_type=~\"$job_type\"}[30s])",
     "legendFormat": "GPU Utilization"
    },
    {
     "expr": "max_over_time(arena_allocated_gpu_memory_of_training_job{job_namespace=~\"$job_namespace\",job_name=~\"$job_name\",job_status=~\"$job_status\",job_type=~\"$job_type\"}[30s])",
     "legendFormat": "Allocated GPU Memory"
    }
   ]
  },
  { "title": "Training Job Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Job Instance Used GPU Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(arena_used_gpu_memory_of_training_job_instance{job_name=~\"$job_name\",job_type=~\"$job_type\",instance_status=\"Running\",job_status=~\"$job_status\"}[10s])",
     "legendFormat": "{{ instance_name }}"
    }
   ]
  },
  {
   "title": "Job Instance Used GPU Memory Percentage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(arena_used_gpu_memory_of_training_job_instance{job_name=~\"$job_name\",job_type=~\"$job_type\",instance_status=\"Running\"} / arena_allocated_gpu_memory_of_training_job_instance{job_name=~\"$job_name\",job_type=~\"$job_type\",instance_status=\"Running\",job_status=~\"$job_status\"} * 100) by (job_name,instance_name)",
     "legendFormat": "{{ instance_name }}"
    }
   ]
  },
  {
   "title": "Job Instance GPU Duty Cycle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "arena_gpu_utilization_of_training_job_instance{job_type=~\"$job_type\",job_name=~\"$job_name\",instance_status=\"Running\",job_status=~\"$job_status\"}",
     "legendFormat": "{{ instance_name }}"
    }
   ]
  }
 ]
}