{
 "title": "Cluster",
 "tags": [
  "arms-k8s",
  "c3c5ffe0a9a0542bab3b3819d891542c7",
  "kube-ai-cluster-details"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "45s",
 "panels": [
  {
   "title": "GPU Summary Of Cluster",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(arena_total_gpus_of_cluster)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Total GPUs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max(arena_allocated_gpus_of_cluster)",
     "legendFormat": "Allocated GPUs"
    },
    {
     "expr": "max(arena_unhealthy_gpus_of_cluster)",
     "legendFormat": "Unhealthy GPUs"
    }
   ]
  },
  {
   "title": "Total GPU Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(max_over_time(arena_used_gpus_of_node[30s]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Total GPU Nodes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unhealthy GPU Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(max_over_time(arena_used_gpus_of_node{node_status!=\"Ready\"}[30s]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Unhealthy GPU Nodes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU Memory(Used/Total)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(arena_used_gpu_memory_of_cluster / arena_total_gpu_memory_of_cluster * 100)",
     "legendFormat": "{{uuid}}  ({{node_name}})"
    }
   ]
  },
  {
   "title": "GPU Memory(Allocated/Total)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(arena_allocated_gpu_memory_of_cluster / arena_total_gpu_memory_of_cluster * 100)",
     "legendFormat": "{{uuid}}  ({{node_name}})"
    }
   ]
  },
  {
   "title": "Training Job Summary Of Cluster",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(max_over_time(arena_duration_of_training_job{job_status=\"PENDING\"}[30s])) or vector(0)",
     "legendFormat": "Pending"
    },
    {
     "expr": "count(max_over_time(arena_duration_of_training_job{job_status=\"RUNNING\"}[30s])) or vector(0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Running",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "count(max_over_time(arena_duration_of_training_job{job_status=\"SUCCEEDED\"}[30s])) or vector(0)",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "count(max_over_time(arena_duration_of_training_job{job_status=\"FAILED\"}[30s])) or vector(0)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "abs(avg(arena_gpu_utilization_of_node))",
     "legendFormat": "{{uuid}}  ({{node_name}})"
    }
   ]
  },
  {
   "title": "GPUs(Allocated/Total)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": " max(arena_allocated_gpus_of_cluster / arena_total_gpus_of_cluster * 100)",
     "legendFormat": "{{uuid}}  ({{node_name}})"
    }
   ]
  }
 ]
}