{
 "title": "Nodes",
 "tags": [
  "arms-k8s",
  "c3c5ffe0a9a0542bab3b3819d891542c7",
  "kube-ai-node-details"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "45s",
 "templating": {
  "list": [
   {
    "name": "gpu_node",
    "query": "label_values(arena_used_gpus_of_node, node_name)"
   },
   {
    "name": "GPU",
    "query": "label_values(nvidia_gpu_memory_used_bytes{node_name=~\"$gpu_node\"}, uuid)"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Node Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(arena_used_gpus_of_node{node_name=~\"$gpu_node\"}[25s])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Allocated GPUs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max_over_time(arena_gpu_utilization_of_node{node_name=~\"$gpu_node\"}[25s])",
     "legendFormat": "GPU Utilization"
    },
    {
     "expr": "max_over_time(arena_allocated_gpu_memory_of_node{node_name=~\"$gpu_node\"}[25s])",
     "legendFormat": "Allocated GPU Memory"
    },
    {
     "expr": "max_over_time(arena_used_gpu_memory_of_node{node_name=~\"$gpu_node\"}[25s])",
     "legendFormat": "Used GPU Memory"
    }
   ]
  },
  {
   "title": "GPU Duty Cycle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(nvidia_gpu_duty_cycle{node_name=~\"$gpu_node\", uuid=~\"$GPU\", allocate_mode!=\"share\"}) by (uuid, node_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{node_name}}/{{uuid}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_memory_used_bytes{node_name=~\"$gpu_node\", uuid=~\"$GPU\",allocate_mode!=\"share\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{node_name}}/{{uuid}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": " GPU Memory Usage Percentage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(nvidia_gpu_memory_used_bytes{node_name=~\"$gpu_node\", uuid=~\"$GPU\",allocate_mode!=\"share\"} / \nnvidia_gpu_memory_total_bytes{node_name=~\"$gpu_node\", uuid=~\"$GPU\",allocate_mode!=\"share\"} * 100) by (node_name,uuid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{node_name}}/{{uuid}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Allocated GPUs Per Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (arena_used_gpus_of_node{node_name=~\"$gpu_node\",node_status=\"Ready\"}) by (node_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{  node_name }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU Number Per Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_num_devices{node_name=~\"$gpu_node\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{node_name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total GPU Memory Per Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "GiB" }
   ],
   "targets": [
    {
     "expr": "floor(nvidia_gpu_memory_total_bytes{node_name=~\"$gpu_node\",allocate_mode!=\"share\"} / 1024 / 1024 / 1024)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{node_name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}