spark.master k8s://https://kubernetes.default.svc:443
spark.submit.deployMode cluster
spark.driver.cores 1
spark.driver.memory 2g
spark.executor.instances 1
spark.executor.cores 1
spark.executor.memory 2g

# Hadoop OSS SDK
spark.hadoop.fs.AbstractFileSystem.oss.impl org.apache.hadoop.fs.aliyun.oss.OSS
spark.hadoop.fs.oss.impl org.apache.hadoop.fs.aliyun.oss.AliyunOSSFileSystem
# Replace it with your oss endpoint. e.g. oss-cn-beijing-internal.aliyuncs.com
spark.hadoop.fs.oss.endpoint {OSS_ENDPOINT}
spark.hadoop.fs.oss.credentials.provider com.aliyun.oss.common.auth.EnvironmentVariableCredentialsProvider
spark.kubernetes.driver.secretKeyRef.OSS_ACCESS_KEY_ID hadoop-oss:OSS_ACCESS_KEY_ID
spark.kubernetes.driver.secretKeyRef.OSS_ACCESS_KEY_SECRET hadoop-oss:OSS_ACCESS_KEY_SECRET
spark.kubernetes.executor.secretKeyRef.OSS_ACCESS_KEY_ID hadoop-oss:OSS_ACCESS_KEY_ID
spark.kubernetes.executor.secretKeyRef.OSS_ACCESS_KEY_SECRET hadoop-oss:OSS_ACCESS_KEY_SECRET

spark.kubernetes.namespace spark
spark.kubernetes.submission.waitAppCompletion false
spark.kubernetes.authenticate.driver.serviceAccountName spark-driver
spark.kubernetes.authenticate.executor.serviceAccountName default

spark.kubernetes.executor.deleteOnTermination false

spark.kubernetes.container.image {SPARK_IMAGE}
spark.kubernetes.container.image.pullPolicy Always
spark.kubernetes.file.upload.path oss://{OSS_BUCKET}/{PATH_TO_UPLOAD_PATH}