apiVersion: v1
name: ack-ai-dev-console
description: ack-ai-dev-console of KubeAI
type: application
kubeVersion: ">=1.18.8-aliyun.1"
version: 1.1.5
appVersion: 1.1.5
keywords:
  - namespace:kube-ai
  - releaseName:ack-ai-dev-console
