{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dev-console-persist.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dev-console-persist.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end -}}