apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubeai:{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
    - ""
    resources: # Get rds secrets in namespace kube-ai
    - secrets # resource name limit
    verbs:
    - get
    - list
  - apiGroups:
    - ""
    resources: # Get user serviceAccounts in namespace kube-ai
    - serviceaccounts #
    verbs:
    - get
  - apiGroups:
    - ""
    resources: # Get datasource and codesource in namespace kube-ai
    - configmaps
    verbs:
    - get
    - update
    - create
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeai:{{ .Release.Namespace }}:{{ .Release.Name }}
rules:
  - apiGroups:
    - ""
    resources:
    - namespaces
    - nodes
    - persistentvolumeclaims
    - events
    - endpoints
    - pods
    - pods/log # Get logs of training jobs
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - deployments
    - services
    verbs:
    - get
    - list
    - watch
    - patch
  - apiGroups:
    - ""
    resources:
    - configmaps # Get and storage job messages 
    verbs:
    - get
    - list
    - watch
    - patch
    - create
    - delete
  - apiGroups:
    - "networking.k8s.io"
    resources:
    - ingresses
    verbs:
    - get
    - list
    - watch
    - create
    - delete
  - apiGroups:
    - "apiextensions.k8s.io"
    resources:
    - customresourcedefinitions
    verbs:
    - get
  - apiGroups:
    - "data.kubeai.alibabacloud.com"
    resources:
    - users
    verbs:
    - get
    - list
  - apiGroups:
    - ""
    - apps
    - extensions
    resources:
    - deployments
    - services
    - replicasets
    - statefulsets
    verbs:
    - get
    - list
    - watch
    - create
    - delete
  - apiGroups:
    - batch
    resources:
    - jobs
    verbs:
    - get
    - list
    - watch
    - create
    - delete
  - apiGroups:
    - ""
    - kubeflow.org
    resources:
    - tfjobs
    - pytorchjobs
    - mpijobs
    verbs:
    - get
    - list
    - watch
    - create
    - delete
  - apiGroups:
    - kai.alibabacloud.com
    resources:
    - '*'
    verbs:
    - get
    - list
    - watch
    - create
    - delete
  - apiGroups:
    - "apps.kubedl.io"
    resources:
    - crons
    - crons/status
    verbs:
    - get
    - list
    - watch
    - create
    - delete
  - apiGroups:
    - "scheduling.sigs.k8s.io"
    resources:
    - "elasticquotatrees"
    verbs:
    - '*'
  - apiGroups:
    - "kubeflow.org"
    resources:
    - notebooks
    - notebooks/status
    verbs:
    - get
    - list
    - watch
    - create
    - delete
  - apiGroups:
    - authentication.k8s.io
    resources:
    - tokenreviews # Create token for user cr
    verbs:
    - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubeai:{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeai:{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ include "dev-console.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeai:{{ .Release.Namespace }}:{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeai:{{ .Release.Namespace }}:{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ include "dev-console.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}