apiVersion: v1
kind: Service
metadata:
  name: {{ include "dev-console.fullname" . }}
  labels:
    {{- include "dev-console.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "dev-console.selectorLabels" . | nindent 4 }}